-- TTLibrary — Bulk import from existingbooks.csv
--
-- BEFORE RUNNING: verify display_name values with:
-- SELECT id, display_name FROM profiles;
--
-- Owner codes used below:
--   'H' = Theresia
--   'T' = Tobias
--   'B' = Both
--
-- Reading status mapping:
--   gelesen        → read
--   ungelesen      → not_read
--   nicht beendet  → reading
--   angefangen     → reading
--   verliehen      → not_read  (lent out; update manually if already read)
--
-- Languages and countries translated from German to English.
-- isbn, description, cover_url, published_year left NULL (not in source data).

DO $$
DECLARE
  theresia_id uuid;
  tobias_id   uuid;
  r           record;
  bid         uuid;
  oid         uuid;
BEGIN
  SELECT id INTO theresia_id FROM profiles WHERE display_name = 'theresia.a.gigon';
  SELECT id INTO tobias_id   FROM profiles WHERE display_name = 'tobiashchristoph';

  IF theresia_id IS NULL THEN
    RAISE EXCEPTION 'Profile "theresia.a.gigon" not found. Run: SELECT id, display_name FROM profiles;';
  END IF;
  IF tobias_id IS NULL THEN
    RAISE EXCEPTION 'Profile "tobiashchristoph" not found. Run: SELECT id, display_name FROM profiles;';
  END IF;

  FOR r IN
    SELECT * FROM (VALUES
      -- title, author, genre[], language, country, owner, reading_status
      ('Fahrt ins Blaue',                                        '* mehrere Autorinnen',          ARRAY['Short Stories']::text[],     'German',  NULL::text,       'H', 'read'),
      ('Moderne französische Erzählungen',                       '* mehrere Autorinnen',          ARRAY['Short Stories']::text[],     'French',  'Germany',        'H', 'not_read'),
      ('Life, the universe and everything',                      'Adams Douglas',                 ARRAY['Science-Fiction']::text[],   'English', 'United Kingdom', 'T', 'not_read'),
      ('The restaurant at the end of the universe',              'Adams Douglas',                 ARRAY['Science-Fiction']::text[],   'English', 'United Kingdom', 'T', 'not_read'),
      ('The reading list',                                       'Adams Sara Nisha',              ARRAY['Contemporary']::text[],      'English', 'United Kingdom', 'H', 'read'),
      ('Little Women',                                           'Alcott Louisa May',             ARRAY['Classics']::text[],          'English', 'United States',  'H', 'read'),
      ('Misbelief',                                              'Ariely Dan',                    ARRAY['Non-Fiction']::text[],       'English', 'United States',  'T', 'not_read'),
      ('The complete stories - volume 1',                        'Asimov Isaac',                  ARRAY['Science-Fiction']::text[],   'English', 'Russia',         'T', 'not_read'),
      ('The testaments',                                         'Atwood Margaret',               ARRAY['Dystopia']::text[],          'English', 'Canada',         'T', 'not_read'),
      ('The handmaid''s tale',                                   'Atwood Margaret',               ARRAY['Dystopia']::text[],          'English', 'Canada',         'T', 'not_read'),
      ('Mr Vertigo',                                             'Auster Paul',                   ARRAY['Fantasy']::text[],           'English', 'United States',  'T', 'not_read'),
      ('Sunset Park',                                            'Auster Paul',                   ARRAY['Contemporary']::text[],      'English', 'United States',  'T', 'not_read'),
      ('4 3 2 1',                                                'Auster Paul',                   ARRAY['Historical Fiction']::text[], 'English', 'United States',  'T', 'not_read'),
      ('Dschinns',                                               'Aydemir Fatma',                 ARRAY['Contemporary']::text[],      'German',  'Germany',        'T', 'not_read'),
      ('Big swiss',                                              'Beagin Jen',                    ARRAY['Contemporary']::text[],      'English', 'United States',  'H', 'read'),
      ('Before we were innocent',                                'Berman Ella',                   ARRAY['Mystery']::text[],           'English', 'United Kingdom', 'H', 'read'),
      ('Ende des Kapitels',                                      'Blake Nicholas',                ARRAY['Mystery']::text[],           'German',  'Ireland',        'H', 'read'),
      ('Firekeeper''s Daughter',                                 'Boulley Angeline',              ARRAY['Mystery']::text[],           'English', 'United States',  'H', 'read'),
      ('When the killing''s done',                               'Boyle T.C.',                    ARRAY['Contemporary']::text[],      'English', 'United States',  'T', 'not_read'),
      ('Fahrenheit 451',                                         'Bradbury Ray',                  ARRAY['Science-Fiction']::text[],   'English', 'United States',  'T', 'not_read'),
      ('Agnes Grey',                                             'Bronte Anne',                   ARRAY['Classics']::text[],          'English', 'United Kingdom', 'T', 'not_read'),
      ('Jane Eyre',                                              'Bronte Charlotte',              ARRAY['Classics']::text[],          'English', 'United Kingdom', 'T', 'not_read'),
      ('Sakrileg',                                               'Brown Dan',                     ARRAY['Thriller']::text[],          'English', 'United States',  'T', 'not_read'),
      ('A clockwork orange',                                     'Burgess Anthony',               ARRAY['Classics']::text[],          'English', 'United Kingdom', 'T', 'not_read'),
      ('Die lodernde Lotte und andere matriarchale Märchen',     'Burschenschaft Furia',          ARRAY['Short Stories']::text[],     'German',  'Austria',        'H', 'not_read'),
      ('Collapse Feminism',                                      'Cappelle Alice',                ARRAY['Non-Fiction']::text[],       'English', 'France',         'T', 'not_read'),
      ('Speaker for the Dead',                                   'Card Orson Scott',              ARRAY['Science-Fiction']::text[],   'English', 'United States',  'T', 'not_read'),
      ('Ender''s Game',                                          'Card Orson Scott',              ARRAY['Science-Fiction']::text[],   'English', 'United States',  'T', 'not_read'),
      ('Small Pleasures',                                        'Chambers Clare',                ARRAY['Contemporary']::text[],      'English', 'United Kingdom', 'H', 'read'),
      ('The perks of being a wallflower',                        'Chbosky Stephen',               ARRAY['Classics']::text[],          'English', 'United States',  'H', 'read'),
      ('Unwell Women',                                           'Cleghorn Elinor',               ARRAY['Non-Fiction']::text[],       'English', NULL,             'T', 'not_read'),
      ('The orange',                                             'Cope Wendy',                    ARRAY['Poetry']::text[],            'English', 'United Kingdom', 'H', 'read'),
      ('Glück mit Soße',                                         'Creech Sharon',                 ARRAY['YA']::text[],                'German',  'United States',  'H', 'read'),
      ('Invisible Women',                                        'Criado Perez Caroline',         ARRAY['Non-Fiction']::text[],       'English', 'United Kingdom', 'T', 'not_read'),
      ('You are nothing',                                        'Dagsson Hugleikur',             ARRAY[]::text[],                    'English', 'Iceland',        'T', 'not_read'),
      ('Charlie and the chocolate Factory',                      'Dahl Roald',                    ARRAY['Classics']::text[],          'English', 'United Kingdom', 'T', 'not_read'),
      ('Don Quixote',                                            'de Cervantes Saavedra Miguel',  ARRAY['Classics']::text[],          'English', 'Spain',          'T', 'not_read'),
      ('Elles vont finir seules avec leurs chats',               'Debest Charlotte',              ARRAY['Non-Fiction']::text[],       'French',  'France',         'H', 'not_read'),
      ('Robinson Crusoe',                                        'Defoe Daniel',                  ARRAY['Classics']::text[],          'English', 'United Kingdom', 'T', 'read'),
      ('Le Reveil du coeur',                                     'd''Epenoux Francois',           ARRAY['Contemporary']::text[],      'French',  'France',         'H', 'not_read'),
      ('David Copperfield',                                      'Dickens Charles',               ARRAY['Classics']::text[],          'English', 'United Kingdom', 'T', 'not_read'),
      ('The holiday bookshop',                                   'Dickens Lucy',                  ARRAY['Romance']::text[],           'English', NULL,             'H', 'read'),
      ('Rebecca',                                                'du Maurier Daphne',             ARRAY['Classics']::text[],          'English', 'United Kingdom', 'H', 'read'),
      ('Die Germanistin',                                        'Duncker Patricia',              ARRAY['Contemporary']::text[],      'German',  'United Kingdom', 'T', 'not_read'),
      ('Mama bitte lern deutsch',                                'Durgun Tahsim',                 ARRAY['Non-Fiction']::text[],       'German',  'Germany',        'H', 'read'),
      ('Der Besuch der alten Dame',                              'Dürrenmatt Friedrich',          ARRAY['Classics']::text[],          'German',  'Switzerland',    'T', 'not_read'),
      ('Physiker',                                               'Dürrenmatt Friedrich',          ARRAY['Classics']::text[],          'German',  'Switzerland',    'T', 'not_read'),
      ('Why I''m no longer talking to white people about race',  'Eddo-Lodge Reni',               ARRAY['Non-Fiction']::text[],       'English', 'United Kingdom', 'T', 'not_read'),
      ('Dave',                                                   'Edelbauer Raphaela',            ARRAY['Science-Fiction']::text[],   'German',  'Austria',        'T', 'not_read'),
      ('The Circle',                                             'Eggers Dave',                   ARRAY['Dystopia']::text[],          'English', 'United States',  'T', 'not_read'),
      ('The mental load',                                        'Emma',                          ARRAY['Non-Fiction']::text[],       'English', 'France',         'T', 'not_read'),
      ('Eines Tages, Baby',                                      'Engelmann Julia',               ARRAY['Poetry']::text[],            'German',  'Germany',        'H', 'read'),
      ('Vie, vieillesse et mort d''une femme du peuple',         'Eribon Didier',                 ARRAY['Non-Fiction']::text[],       'French',  'France',         'H', 'reading'),
      ('Can we all be feminists?',                               'Eric-Udorie June',              ARRAY['Non-Fiction']::text[],       'English', 'United States',  'H', 'reading'),
      ('Middlesex',                                              'Eugenides Jeffrey',             ARRAY['Contemporary']::text[],      'English', 'United States',  'H', 'read'),
      ('Girl, Woman, Other',                                     'Evaristo Bernardine',           ARRAY['Short Stories']::text[],     'English', 'United Kingdom', 'H', 'read'),
      ('The Trees',                                              'Everett Percival',              ARRAY['Mystery']::text[],           'English', 'United States',  'H', 'read'),
      ('James',                                                  'Everett Percival',              ARRAY['Historical Fiction']::text[], 'English', 'United States',  'H', 'read'),
      ('The fifth Science',                                      'Exurbia',                       ARRAY['Science-Fiction']::text[],   'English', NULL,             'T', 'not_read'),
      ('The prince of milk',                                     'Exurbia',                       ARRAY['Science-Fiction']::text[],   'English', NULL,             'T', 'not_read'),
      ('Die Wut die bleibt',                                     'Fallwickl Mareike',             ARRAY['Contemporary']::text[],      'German',  'Austria',        'H', 'not_read'),
      ('Let me go mad in my own way',                            'Feeney Elaine',                 ARRAY['Contemporary']::text[],      'English', 'Ireland',        'H', 'read'),
      ('polysecure',                                             'Fern Jessica',                  ARRAY['Non-Fiction']::text[],       'English', NULL,             'H', 'not_read'),
      ('The great gatsby',                                       'Fitzgerald F. Scott',           ARRAY['Classics']::text[],          'English', 'United States',  'T', 'read'),
      ('Certifié humaine',                                       'Formica Dora',                  ARRAY['Dystopia']::text[],          'French',  'Switzerland',    'T', 'not_read'),
      ('Tagebuch',                                               'Frank Anne',                    ARRAY['Non-Fiction']::text[],       'German',  'Germany',        'T', 'not_read'),
      ('The rose, thistle and shamrock',                         'Freiligrath Ferdinand',         ARRAY['Poetry']::text[],            'English', 'Germany',        'T', 'not_read'),
      ('Andorra',                                                'Frisch Max',                    ARRAY['Classics']::text[],          'German',  'Switzerland',    'T', 'not_read'),
      ('Die Kunst des Liebens',                                  'Fromm Erich',                   ARRAY['Non-Fiction']::text[],       'German',  'Germany',        'H', 'reading'),
      ('Coraline',                                               'Gaiman Neil',                   ARRAY['Horror']::text[],            'English', 'United Kingdom', 'H', 'read'),
      ('Jung Indien',                                            'Gandhi Mahatma',                ARRAY[]::text[],                    'German',  NULL,             'T', 'not_read'),
      ('Lessons in Chemistry',                                   'Garmus Bonnie',                 ARRAY['Historical Fiction']::text[], 'English', 'United States',  'H', 'not_read'),
      ('Women don''t owe you pretty',                            'Given Florence',                ARRAY['Non-Fiction']::text[],       'English', 'United Kingdom', 'H', 'read'),
      ('Glück ist eine Gleichung mit 7',                         'Goldberg Sloan Holy',           ARRAY['YA']::text[],                'German',  'United States',  'H', 'read'),
      ('Olga dies dreaming',                                     'González Xóchitl',              ARRAY['Contemporary']::text[],      'English', 'United States',  'H', 'read'),
      ('They call it love',                                      'Gotby Alva',                    ARRAY['Non-Fiction']::text[],       'English', 'United Kingdom', 'T', 'reading'),
      ('Sie lieben',                                             'Grassmann Alexa',               ARRAY['Non-Fiction']::text[],       'German',  'Germany',        'H', 'read'),
      ('An abundance of Katherines',                             'Green John',                    ARRAY['YA']::text[],                'English', 'United States',  'H', 'read'),
      ('Looking for alaska',                                     'Green John',                    ARRAY['YA']::text[],                'English', 'United States',  'H', 'read'),
      ('will grayson will grayson',                              'Green John',                    ARRAY['YA']::text[],                'English', 'United States',  'T', 'read'),
      ('The curious incident of the dog in the night-time',      'Haddon Mark',                   ARRAY['YA']::text[],                'English', 'United Kingdom', 'H', 'read'),
      ('The midnight library',                                   'Haig Matt',                     ARRAY['Fantasy']::text[],           'English', 'United Kingdom', 'H', 'read'),
      ('Sapiens - a brief history of humankind',                 'Harari Yuval Noah',             ARRAY['Non-Fiction']::text[],       'English', 'Israel',         'T', 'not_read'),
      ('Nexus',                                                  'Harari Yuval Noah',             ARRAY['Non-Fiction']::text[],       'German',  'Israel',         'T', 'not_read'),
      ('The end of Faith',                                       'Harris Sam',                    ARRAY['Non-Fiction']::text[],       'English', 'United States',  'T', 'not_read'),
      ('Bahnwärter Thiel',                                       'Hauptmann Gerhart',             ARRAY['Classics']::text[],          'German',  'Germany',        'T', 'not_read'),
      ('Vor Sonnenaufgang',                                      'Hauptmann Gerhart',             ARRAY['Classics']::text[],          'German',  'Germany',        'T', 'not_read'),
      ('Catch-22',                                               'Heller Joseph',                 ARRAY['Classics']::text[],          'English', 'United States',  'T', 'not_read'),
      ('The old man and the Sea',                                'Hemingway Ernest',              ARRAY['Classics']::text[],          'English', 'United States',  'T', 'read'),
      ('The snows of Kilimanjaro',                               'Hemingway Ernest',              ARRAY['Classics']::text[],          'English', 'United States',  'T', 'not_read'),
      ('Dune',                                                   'Herbert Frank',                 ARRAY['Science-Fiction']::text[],   'English', 'United States',  'T', 'not_read'),
      ('People we meet on vacation',                             'Henry Emily',                   ARRAY['Romance']::text[],           'English', 'United States',  'H', 'read'),
      ('Book Lovers',                                            'Henry Emily',                   ARRAY['Romance']::text[],           'English', 'United States',  'H', 'read'),
      ('Funny Story',                                            'Henry Emily',                   ARRAY['Romance']::text[],           'English', 'United States',  'H', 'read'),
      ('Delilah Green doesn''t care',                            'Herring Blake Ashley',          ARRAY['Romance']::text[],           'English', 'United States',  'H', 'read'),
      ('Astrid Parker doesn''t fail',                            'Herring Blake Ashley',          ARRAY['Romance']::text[],           'English', 'United States',  'H', 'read'),
      ('Iris Kelly doesn''t date',                               'Herring Blake Ashley',          ARRAY['Romance']::text[],           'English', 'United States',  'H', 'read'),
      ('Tschick',                                                'Herrndorf Wolfgang',            ARRAY['YA']::text[],                'German',  'Germany',        'T', 'read'),
      ('Biko''s Ghost - the iconography of Black Consciousness', 'Hill Shannen L',                ARRAY['Historical Fiction']::text[], 'English', NULL,             'T', 'not_read'),
      ('The legend of Zelda',                                    'Himekawa Akira',                ARRAY['Comic']::text[],             'English', 'Japan',          'T', 'not_read'),
      ('Eleanor Oliphant is completely fine',                    'Honeyman Gail',                 ARRAY['Contemporary']::text[],      'English', 'United Kingdom', 'H', 'read'),
      ('Communion',                                              'Hooks Bell',                    ARRAY['Non-Fiction']::text[],       'English', 'United States',  'H', 'not_read'),
      ('Fever Pitch',                                            'Hornby Nick',                   ARRAY['Contemporary']::text[],      'English', 'United Kingdom', 'T', 'not_read'),
      ('High Fidelity',                                          'Hornby Nick',                   ARRAY['Contemporary']::text[],      'English', 'United Kingdom', 'T', 'not_read'),
      ('How to be good',                                         'Hornby Nick',                   ARRAY['Contemporary']::text[],      'English', 'United Kingdom', 'T', 'not_read'),
      ('31 songs',                                               'Hornby Nick',                   ARRAY['Non-Fiction']::text[],       'English', 'United Kingdom', 'T', 'not_read'),
      ('About a boy',                                            'Hornby Nick',                   ARRAY['Contemporary']::text[],      'English', 'United Kingdom', 'H', 'read'),
      ('A thousand splendid suns',                               'Hosseini Khaled',               ARRAY['Historical Fiction']::text[], 'English', 'Afghanistan',    'T', 'not_read'),
      ('Where the wild winds are',                               'Hunt Nick',                     ARRAY['Non-Fiction']::text[],       'English', 'United Kingdom', 'H', 'not_read'),
      ('Brave new world',                                        'Huxley Aldous',                 ARRAY['Science-Fiction']::text[],   'English', 'United Kingdom', 'T', 'not_read'),
      ('Voices',                                                 'Indridason Arnaldur',           ARRAY['Mystery']::text[],           'English', 'Iceland',        'T', 'not_read'),
      ('We have always lived in the castle',                     'Jackson Shirley',               ARRAY[]::text[],                    'English', NULL,             'H', 'read'),
      ('Little Book of Vivienne Westwood',                       'Johnson Glenys',                ARRAY['Non-Fiction']::text[],       'German',  NULL,             'H', 'not_read'),
      ('Wie wir lieben',                                         'Karig Friedemann',              ARRAY['Non-Fiction']::text[],       'German',  'Germany',        'H', 'read'),
      ('the sun and her flowers',                                'Kaur Rupi',                     ARRAY['Poetry']::text[],            'English', 'Canada',         'H', 'read'),
      ('milk and honey',                                         'Kaur Rupi',                     ARRAY['Poetry']::text[],            'English', 'Canada',         'H', 'read'),
      ('Small things like these',                                'Keegan Claire',                 ARRAY['Historical Fiction']::text[], 'English', 'Ireland',        'T', 'read'),
      ('Antarctica',                                             'Keegan Claire',                 ARRAY['Short Stories']::text[],     'English', 'Ireland',        'H', 'read'),
      ('Mein Algorithmus und Ich',                               'Kehlmann Daniel',               ARRAY['Non-Fiction']::text[],       'German',  'Germany',        'T', 'not_read'),
      ('Schindlers Liste',                                       'Keneally Thomas',               ARRAY['Non-Fiction']::text[],       'German',  'Australia',      'T', 'not_read'),
      ('How to be an Antiracist',                                'Kendi Ibram X.',                ARRAY['Non-Fiction']::text[],       'English', 'United States',  'T', 'not_read'),
      ('Flowers for Algernon',                                   'Keyes Daniel',                  ARRAY['Classics']::text[],          'English', 'United States',  'T', 'not_read'),
      ('Love Machine',                                           'Kiviger Jeanne',                ARRAY['Contemporary']::text[],      'French',  'France',         'H', 'read'),
      ('The house in the cerulean Sea',                          'Klune TJ',                      ARRAY['Fantasy']::text[],           'English', 'United States',  'H', 'read'),
      ('Sunrise',                                                'Kühlmeier Michael',             ARRAY['YA']::text[],                'German',  'Austria',        'T', 'not_read'),
      ('Der Weg der Wahrhaftigkeit',                             'Konfuzius',                     ARRAY['Non-Fiction']::text[],       'German',  'China',          'T', 'not_read'),
      ('From the mixed up files of Mrs. Basil E. Frankweiler',  'Konigsburg E.L.',               ARRAY['YA']::text[],                'English', 'United States',  'T', 'read'),
      ('Kult-Kanzler Kreisky',                                   'Kotanko Christoph',             ARRAY['Non-Fiction']::text[],       'German',  'Austria',        'H', 'read'),
      ('To kill a mockingbird',                                  'Lee Harper',                    ARRAY['Historical Fiction']::text[], 'English', 'United States',  'T', 'not_read'),
      ('Go set a watchman',                                      'Lee Harper',                    ARRAY['Historical Fiction']::text[], 'English', 'United States',  'T', 'not_read'),
      ('Was man von hier aus sehen kann',                        'Leky Mariana',                  ARRAY['Contemporary']::text[],      'German',  'Germany',        'H', 'read'),
      ('Die Entpuppung',                                         'Lemsine Aicha',                 ARRAY['Historical Fiction']::text[], 'German',  'Algeria',        'H', 'not_read'),
      ('The golden notebook',                                    'Lessing Doris',                 ARRAY['Classics']::text[],          'English', 'United Kingdom', 'H', 'not_read'),
      ('The fifth child',                                        'Lessing Doris',                 ARRAY['Horror']::text[],            'English', 'United Kingdom', 'T', 'not_read'),
      ('another day',                                            'Levithan David',                ARRAY['YA']::text[],                'English', 'United States',  'T', 'not_read'),
      ('everyday',                                               'Levithan David',                ARRAY['YA']::text[],                'English', 'United States',  'T', 'not_read'),
      ('boy meets boy',                                          'Levithan David',                ARRAY['YA']::text[],                'English', 'United States',  'T', 'not_read'),
      ('August Blue',                                            'Levy Deborah',                  ARRAY['Contemporary']::text[],      'English', 'United Kingdom', 'H', 'not_read'),
      ('The Positions of Spoons and Other Intimacies',           'Levy Deborah',                  ARRAY['Non-Fiction']::text[],       'English', 'United Kingdom', 'H', 'reading'),
      ('Freunde lieben',                                         'Liebl Ole',                     ARRAY['Non-Fiction']::text[],       'German',  'Germany',        'H', 'not_read'),
      ('Ronja Räubertochter',                                    'Lindgren Astrid',               ARRAY['YA']::text[],                'German',  'Sweden',         'H', 'read'),
      ('Kalle Blomquist',                                        'Lindgren Astrid',               ARRAY['YA']::text[],                'German',  'Sweden',         'T', 'not_read'),
      ('A house in the sky',                                     'Lindhout Amanda',               ARRAY['Biographie']::text[],        'English', 'Canada',         'T', 'not_read'),
      ('Last night at the telegraph club',                       'Lo Malinda',                    ARRAY['Romance']::text[],           'English', 'China',          'H', 'read'),
      ('The princess saves herself in this one',                 'Lovelace Amanda',               ARRAY['Poetry']::text[],            'English', 'United States',  'H', 'read'),
      ('The end of everything',                                  'Mack Katie',                    ARRAY['Non-Fiction']::text[],       'English', 'United States',  'T', 'not_read'),
      ('The Hike',                                               'Magary Drew',                   ARRAY['Fantasy']::text[],           'English', 'United States',  'T', 'not_read'),
      ('A clash of Kings',                                       'Martin George R. R.',           ARRAY['Fantasy']::text[],           'English', 'United States',  'T', 'not_read'),
      ('A Game of Thrones',                                      'Martin George R. R.',           ARRAY['Fantasy']::text[],           'English', 'United States',  'T', 'reading'),
      ('Leurs enfants après eux',                                'Mathieu Nicolas',               ARRAY['Contemporary']::text[],      'French',  'France',         'H', 'not_read'),
      ('Mein Weg vom Kongo nach Europa',                         'Mbolela Emmanuel',              ARRAY['Non-Fiction']::text[],       'German',  'Congo',          'T', 'not_read'),
      ('Apeirogon',                                              'McCann Colum',                  ARRAY['Historical Fiction']::text[], 'English', 'Ireland',        'H', 'reading'),
      ('Slug',                                                   'Mcnish Hollie',                 ARRAY['Poetry']::text[],            'English', 'United Kingdom', 'H', 'read'),
      ('Red, White and Royal Blue',                              'McQuiston Casey',               ARRAY['Romance']::text[],           'English', 'United States',  'H', 'read'),
      ('One last stop',                                          'McQuiston Casey',               ARRAY['Romance']::text[],           'English', 'United States',  'H', 'read'),
      ('I kissed Shara Wheeler',                                 'McQuiston Casey',               ARRAY['YA']::text[],                'English', 'United States',  'H', 'read'),
      ('The pairing',                                            'McQuiston Casey',               ARRAY['Romance']::text[],           'English', 'United States',  'H', 'read'),
      ('Bittere Wunder',                                         'Meldrum Christina',             ARRAY['YA']::text[],                'German',  'United States',  'H', 'reading'),
      ('Blue Sisters',                                           'Mellors Coco',                  ARRAY['Contemporary']::text[],      'English', 'United Kingdom', 'H', 'read'),
      ('The Song of Achilles',                                   'Miller Madeline',               ARRAY['Fantasy']::text[],           'English', 'United States',  'T', 'read'),
      ('Circe',                                                  'Miller Madeline',               ARRAY['Fantasy']::text[],           'English', 'United States',  'T', 'not_read'),
      ('Coming of age in Mississippi',                           'Moody Anne',                    ARRAY['Non-Fiction']::text[],       'English', 'United States',  'T', 'not_read'),
      ('Sette racconti',                                         'Moravia Alberto',               ARRAY['Short Stories']::text[],     'Italian', 'Italy',          'T', 'not_read'),
      ('What if?',                                               'Munroe Randall',                ARRAY['Non-Fiction']::text[],       'English', 'United States',  'T', 'not_read'),
      ('Convenience store woman',                                'Murata Sayaka',                 ARRAY['Contemporary']::text[],      'English', 'Japan',          'H', 'read'),
      ('Liebesgedichte',                                         'Neruda Pablo',                  ARRAY['Poetry']::text[],            'German',  'Chile',          'H', 'not_read'),
      ('Us',                                                     'Nicholls David',                ARRAY['Romance']::text[],           'English', 'United Kingdom', 'T', 'not_read'),
      ('One day',                                                'Nicholls David',                ARRAY['Romance']::text[],           'English', 'United Kingdom', 'H', 'read'),
      ('The silk house',                                         'Nunn Kayte',                    ARRAY['Mystery']::text[],           'English', 'United States',  'H', 'read'),
      ('A promised land',                                        'Obama Barack',                  ARRAY['Biographie']::text[],        'English', 'United States',  'T', 'not_read'),
      ('The rachel incident',                                    'O''Donoghue Caroline',          ARRAY['Contemporary']::text[],      'English', 'Ireland',        'H', 'read'),
      ('Down and out in Paris and London',                       'Orwell George',                 ARRAY['Non-Fiction']::text[],       'English', 'United Kingdom', 'T', 'not_read'),
      ('Animal Farm',                                            'Orwell George',                 ARRAY['Classics']::text[],          'English', 'United Kingdom', 'T', 'not_read'),
      ('Nineteen Eighty-Four',                                   'Orwell George',                 ARRAY['Classics']::text[],          'English', 'United Kingdom', 'T', 'not_read'),
      ('The man who died twice',                                 'Osman Richard',                 ARRAY['Mystery']::text[],           'English', 'United Kingdom', 'H', 'read'),
      ('The bullet that missed',                                 'Osman Richard',                 ARRAY['Mystery']::text[],           'English', 'United Kingdom', 'H', 'read'),
      ('The Thursday murder club',                               'Osman Richard',                 ARRAY['Mystery']::text[],           'English', 'United Kingdom', 'H', 'read'),
      ('The last devil to die',                                  'Osman Richard',                 ARRAY['Mystery']::text[],           'English', 'United Kingdom', 'H', 'read'),
      ('Adam ist jetzt mit Eva befreundet',                      'Overstreet Wylie',              ARRAY['Non-Fiction']::text[],       'German',  'United States',  'T', 'not_read'),
      ('Where the crawdads sing',                                'Owens Delia',                   ARRAY['Historical Fiction']::text[], 'English', 'United States',  'H', 'read'),
      ('The scramble for Africa',                                'Pakenham Thomas',               ARRAY['Non-Fiction']::text[],       'English', 'United Kingdom', 'T', 'not_read'),
      ('Fight Club',                                             'Palahniuk Chuck',               ARRAY['Classics']::text[],          'English', 'United States',  'T', 'not_read'),
      ('Snow',                                                   'Pamuk Orhan',                   ARRAY['Contemporary']::text[],      'English', 'Turkey',         'T', 'not_read'),
      ('Enteignete Kunst',                                       'Pawlowsky Verena',              ARRAY['Non-Fiction']::text[],       'German',  'Austria',        'H', 'not_read'),
      ('Mad honey',                                              'Picoult Jodi',                  ARRAY['Mystery']::text[],           'English', 'United States',  'H', 'read'),
      ('Elena Knows',                                            'Piñeiro Claudia',               ARRAY['Contemporary']::text[],      'English', 'Argentina',      'T', 'read'),
      ('The bell jar',                                           'Plath Sylvia',                  ARRAY['Classics']::text[],          'English', 'United States',  'T', 'not_read'),
      ('Ariel',                                                  'Plath Sylvia',                  ARRAY['Poetry']::text[],            'English', 'United States',  'H', 'reading'),
      ('The tell-tale heart',                                    'Poe Edgar Allan',               ARRAY['Classics']::text[],          'English', 'United States',  'T', 'not_read'),
      ('Les royaumes du nord',                                   'Pullman Philip',                ARRAY['YA']::text[],                'French',  'United Kingdom', 'H', 'not_read'),
      ('The revenant',                                           'Punke Michael',                 ARRAY['Historical Fiction']::text[], 'English', 'United States',  'T', 'not_read'),
      ('Ophelia after all',                                      'Racquel Marie',                 ARRAY['YA']::text[],                'English', 'United States',  'H', 'read'),
      ('Der fliegende Berg',                                     'Ransmayr Christoph',            ARRAY['Contemporary']::text[],      'German',  'Austria',        'T', 'not_read'),
      ('The seven husbands of Evelyn Hugo',                      'Reid Taylor Jenkins',           ARRAY['Historical Fiction']::text[], 'English', 'United States',  'H', 'read'),
      ('Carrie Soto is back',                                    'Reid Taylor Jenkins',           ARRAY['Historical Fiction']::text[], 'English', 'United States',  'H', 'read'),
      ('Malibu rising',                                          'Reid Taylor Jenkins',           ARRAY['Historical Fiction']::text[], 'English', 'United States',  'H', 'read'),
      ('The wave',                                               'Rhue Morton',                   ARRAY['Classics']::text[],          'English', 'Germany',        'T', 'read'),
      ('If we were villains',                                    'Rio M. L.',                     ARRAY['Mystery']::text[],           'English', 'United Kingdom', 'H', 'read'),
      ('Winter stories',                                         'Rishoi Ingvild',                ARRAY['Short Stories']::text[],     'English', 'Norway',         'H', 'not_read'),
      ('The chaos of longing',                                   'Robinson K.Y.',                 ARRAY['Poetry']::text[],            'English', 'United States',  'H', 'read'),
      ('Intermezzo',                                             'Rooney Sally',                  ARRAY['Contemporary']::text[],      'English', 'Ireland',        'H', 'read'),
      ('Beautiful world where are you',                          'Rooney Sally',                  ARRAY['Contemporary']::text[],      'English', 'Ireland',        'H', 'read'),
      ('Eleanor and Park',                                       'Rowell Rainbow',                ARRAY['YA']::text[],                'English', 'United States',  'T', 'read'),
      ('Fangirl',                                                'Rowell Rainbow',                ARRAY['YA']::text[],                'English', 'United States',  'H', 'read'),
      ('Harry Potter und der Stein der Weisen',                  'Rowling J. K.',                 ARRAY['Fantasy']::text[],           'German',  'United States',  'B', 'read'),
      ('Harry Potter and the Chamber of Secrets',                'Rowling J. K.',                 ARRAY['Fantasy']::text[],           'English', 'United States',  'T', 'read'),
      ('Harry Potter and the Prisoner of Azkaban',               'Rowling J. K.',                 ARRAY['Fantasy']::text[],           'English', 'United States',  'T', 'read'),
      ('The tales of beedle the bard',                           'Rowling J. K.',                 ARRAY['Fantasy']::text[],           'English', 'United States',  'T', 'not_read'),
      ('Quidditch through the ages',                             'Rowling J. K.',                 ARRAY['Fantasy']::text[],           'English', 'United States',  'T', 'not_read'),
      ('Harry Potter and the Half-Blood Prince',                 'Rowling J. K.',                 ARRAY['Fantasy']::text[],           'English', 'United States',  'T', 'read'),
      ('Aristotle and Dante discover the secrets of the universe','Saenz Benjamin Alire',         ARRAY['YA']::text[],                'English', 'United States',  'T', 'read'),
      ('Aristotle and Dante dive into the waters of the world',  'Saenz Benjamin Alire',         ARRAY['YA']::text[],                'English', 'United States',  'T', 'read'),
      ('The catcher in the rye',                                 'Salinger J.D.',                 ARRAY['Classics']::text[],          'English', 'United States',  'T', 'read'),
      ('Cytonic',                                                'Sanderson Brandon',             ARRAY['Science-Fiction']::text[],   'English', 'United States',  'T', 'not_read'),
      ('Starsight',                                              'Sanderson Brandon',             ARRAY['Science-Fiction']::text[],   'English', 'United States',  'T', 'not_read'),
      ('Skyward',                                                'Sanderson Brandon',             ARRAY['Science-Fiction']::text[],   'English', 'United States',  'T', 'not_read'),
      ('Echtzeitalter',                                          'Schachinger Tonio',             ARRAY['Contemporary']::text[],      'German',  'Austria',        'T', 'not_read'),
      ('dreimeterdreißig',                                       'Scheiber Jaqueline',            ARRAY['Contemporary']::text[],      'German',  'Austria',        'H', 'read'),
      ('The lost cafe Schindler',                                'Schindler Meriel',              ARRAY['Non-Fiction']::text[],       'English', 'Austria',        'T', 'not_read'),
      ('Die Alpen',                                              'Schlender',                     ARRAY['Short Stories']::text[],     'German',  'Germany',        'T', 'not_read'),
      ('Der Vorleser',                                           'Schlink Bernhard',              ARRAY['Classics']::text[],          'German',  'Germany',        'T', 'read'),
      ('The beginning of everything',                            'Schneider Robyn',               ARRAY['YA']::text[],                'English', 'United States',  'T', 'not_read'),
      ('Barca oder die Kunst des schönen Spiels',                'Schulze-Marmeling Dietrich',    ARRAY['Non-Fiction']::text[],       'German',  NULL,             'T', 'not_read'),
      ('The invisible life of Addie LaRue',                      'Schwab V.E.',                   ARRAY['Fantasy']::text[],           'English', 'United Kingdom', 'H', 'read'),
      ('After Sappho',                                           'Schwartz Selby Wynn',           ARRAY['Historical Fiction']::text[], 'English', 'United States',  'H', 'read'),
      ('The forty Rules of Love',                                'Shafak Elif',                   ARRAY['Historical Fiction']::text[], 'English', 'Turkey',         'H', 'read'),
      ('Island of the missing tree',                             'Shafak Elif',                   ARRAY['Historical Fiction']::text[], 'English', 'Turkey',         'H', 'not_read'),
      ('10 Minutes, 38 Seconds in the Strange world',            'Shafak Elif',                   ARRAY['Contemporary']::text[],      'English', 'Turkey',         'T', 'read'),
      ('There are waters in the sky',                            'Shafak Elif',                   ARRAY['Historical Fiction']::text[], 'English', 'Turkey',         'H', 'read'),
      ('The bastard of Istanbul',                                'Shafak Elif',                   ARRAY['Historical Fiction']::text[], 'English', 'Turkey',         'H', 'not_read'),
      ('Love Poems',                                             'Shakespeare',                   ARRAY['Poetry']::text[],            'English', 'United Kingdom', 'H', 'not_read'),
      ('Bi - the hidden culture, history and science of bisexuality','Shaw Julia',                ARRAY['Non-Fiction']::text[],       'English', 'Germany',        'H', 'not_read'),
      ('Violets',                                                'Shin Kyung-Sook',               ARRAY['Historical Fiction']::text[], 'English', 'South Korea',    'T', 'not_read'),
      ('She and her cat',                                        'Shinkai Makoto, Nagakawa Naruki',ARRAY['Short Stories']::text[],    'English', 'Japan',          'H', 'read'),
      ('Autumn',                                                 'Smith Ali',                     ARRAY['Contemporary']::text[],      'English', 'United Kingdom', 'H', 'read'),
      ('East of Eden',                                           'Steinbeck John',                ARRAY['Classics']::text[],          'English', 'United States',  'T', 'reading'),
      ('Cannery row',                                            'Steinbeck John',                ARRAY['Classics']::text[],          'English', 'United States',  'T', 'read'),
      ('The pearl',                                              'Steinbeck John',                ARRAY['Classics']::text[],          'English', 'United States',  'T', 'not_read'),
      ('The red pony',                                           'Steinbeck John',                ARRAY['Classics']::text[],          'English', 'United States',  'T', 'not_read'),
      ('Travels with Charley in search of America',              'Steinbeck John',                ARRAY['Non-Fiction']::text[],       'English', 'United States',  'T', 'not_read'),
      ('The grapes of wrath',                                    'Steinbeck John',                ARRAY['Classics']::text[],          'English', 'United States',  'T', 'not_read'),
      ('The vigilante',                                          'Steinbeck John',                ARRAY['Short Stories']::text[],     'English', 'United States',  'T', 'not_read'),
      ('Trägerische Stille',                                     'Steinhöfel Andreas',            ARRAY['YA']::text[],                'German',  'Germany',        'T', 'not_read'),
      ('Das Parfum',                                             'Süskind Patrick',               ARRAY['Classics']::text[],          'German',  'Germany',        'T', 'read'),
      ('Small World',                                            'Suter Martin',                  ARRAY['Contemporary']::text[],      'German',  'Switzerland',    'H', 'read'),
      ('Huber spannt aus',                                       'Suter Martin',                  ARRAY['Contemporary']::text[],      'German',  'Switzerland',    'H', 'not_read'),
      ('Allmen und der Koi',                                     'Suter Martin',                  ARRAY['Krimi']::text[],             'German',  'Switzerland',    'H', 'read'),
      ('Die dunkle Seite des Mondes',                            'Suter Martin',                  ARRAY['Contemporary']::text[],      'German',  'Switzerland',    'H', 'read'),
      ('Die Waffen nieder!',                                     'Suttner von Bertha',            ARRAY['Historical Fiction']::text[], 'German',  'Austria',        'T', 'not_read'),
      ('Gulliver''s Travels',                                    'Swift Jonathan',                ARRAY['Classics']::text[],          'English', 'Ireland',        'T', 'read'),
      ('The secret History',                                     'Tartt Donna',                   ARRAY['Mystery']::text[],           'English', 'United States',  'H', 'read'),
      ('The Goldfinch',                                          'Tartt Donna',                   ARRAY['Contemporary']::text[],      'English', NULL,             'T', 'not_read'),
      ('Die schönste Version',                                   'Thomas Ruth-Maria',             ARRAY['Contemporary']::text[],      'German',  'Germany',        'H', 'not_read'),
      ('The hate u give',                                        'Thomas Angie',                  ARRAY['YA']::text[],                'English', 'United States',  'T', 'not_read'),
      ('Ein schönes Ausländerkind',                              'Toxische Pommes',               ARRAY['Contemporary']::text[],      'German',  'Austria',        'H', 'not_read'),
      ('Katzen - wie sie erst uns und dann die Welt erobern',    'Tucker Abigail',                ARRAY['Non-Fiction']::text[],       'German',  'United States',  'H', 'not_read'),
      ('Fathers and Sons',                                       'Turgenev',                      ARRAY['Classics']::text[],          'English', 'Russia',         'T', 'not_read'),
      ('The body keeps the score',                               'Van der Kolk Bessel',           ARRAY['Non-Fiction']::text[],       'English', 'United States',  'H', 'not_read'),
      ('It''s kind of a funny story',                            'Vizzini Ned',                   ARRAY['YA']::text[],                'English', 'United States',  'T', 'not_read'),
      ('Der Hase mit den Bernsteinaugen',                        'de Waal Edmund',                ARRAY['Historical Fiction']::text[], 'German',  'Austria',        'H', 'not_read'),
      ('The color purple',                                       'Walker Alice',                  ARRAY['Historical Fiction']::text[], 'English', 'United States',  'T', 'not_read'),
      ('The martian',                                            'Weir Andy',                     ARRAY['Science-Fiction']::text[],   'English', 'United States',  'T', 'not_read'),
      ('Artemis',                                                'Weir Andy',                     ARRAY['Science-Fiction']::text[],   'English', 'United States',  'T', 'not_read'),
      ('Project Hail Mary',                                      'Weir Andy',                     ARRAY['Science-Fiction']::text[],   'English', 'United States',  'T', 'not_read'),
      ('Die philosophische Hintertreppe',                        'Weischedel Wilhelm',            ARRAY['Non-Fiction']::text[],       'German',  'Germany',        'T', 'not_read'),
      ('Vom Ende der Einsamkeit',                                'Wells Benedict',                ARRAY['Contemporary']::text[],      'German',  'Germany',        'H', 'read'),
      ('Educated',                                               'Westover Tara',                 ARRAY['Non-Fiction']::text[],       'English', 'United States',  'T', 'not_read'),
      ('Oranges are not the only fruit',                         'Winterson Jeanette',            ARRAY['Contemporary']::text[],      'English', 'United Kingdom', 'H', 'not_read'),
      ('Biko',                                                   'Woods Donald',                  ARRAY['Non-Fiction']::text[],       'English', 'South Africa',   'T', 'not_read'),
      ('I am Malala',                                            'Yousafzai Malala',              ARRAY['Biographie']::text[],        'English', 'Pakistan',       'T', 'not_read'),
      ('Tomorrow, and Tomorrow, and Tomorrow',                   'Zevin Gabrielle',               ARRAY['Contemporary']::text[],      'English', 'United States',  'T', 'not_read'),
      ('The book thief',                                         'Zusak Martin',                  ARRAY['Historical Fiction']::text[], 'English', 'Australia',      'T', 'not_read'),
      ('Normal und die zero heros',                              'Kling Marc-Uwe',                ARRAY['Comic']::text[],             'German',  'Germany',        'T', 'not_read')
    ) AS t(title, author, genre, language, country, owner, rstatus)
  LOOP
    -- Determine primary owner for added_by
    oid := CASE r.owner WHEN 'H' THEN theresia_id ELSE tobias_id END;

    INSERT INTO books (title, author, genre, language, country, added_by)
    VALUES (r.title, r.author, r.genre, r.language, r.country, oid)
    RETURNING id INTO bid;

    IF r.owner = 'B' THEN
      -- Owned by both (Harry Potter #1 German edition)
      INSERT INTO book_owners (book_id, profile_id) VALUES (bid, theresia_id), (bid, tobias_id);
      INSERT INTO reading_status (book_id, profile_id, status)
      VALUES (bid, theresia_id, r.rstatus::reading_status_enum),
             (bid, tobias_id,   r.rstatus::reading_status_enum);
    ELSE
      INSERT INTO book_owners (book_id, profile_id) VALUES (bid, oid);
      INSERT INTO reading_status (book_id, profile_id, status)
      VALUES (bid, oid, r.rstatus::reading_status_enum);
    END IF;
  END LOOP;

  RAISE NOTICE 'Import complete.';
END $$;
